name: music
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  display_mode:
    path: display_mode

  flutter_native_splash: ^2.4.3
  go_router: ^14.6.2
  responsive_framework: ^1.5.1
  crypto: ^3.0.6
  path: ^1.9.0
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  http: ^1.2.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  palette_generator: ^0.3.3+5
  image: ^4.5.2
  audio_service: ^0.18.16
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.8
  metadata_god: ^1.0.0
  equatable: ^2.0.7
  youtube_explode_dart: ^2.3.6
  rxdart: ^0.28.0
  async: ^2.11.0
  package_info_plus: ^8.1.2
  isar: 3.1.0+1
  fuzzywuzzy: ^1.2.0
  dart_des: ^1.0.2
  html_unescape: ^2.0.0
  logging: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Unageo
      fonts:
        - asset: fonts/Unageo/Unageo-Regular.ttf
          weight: 400
        - asset: fonts/Unageo/Unageo-Medium.ttf
          weight: 500
        - asset: fonts/Unageo/Unageo-Semibold.ttf
          weight: 600
        - asset: fonts/Unageo/Unageo-Bold.ttf
          weight: 700
        - asset: fonts/Unageo/Unageo-Extrabold.ttf
          weight: 800
        - asset: fonts/Unageo/Unageo-Black.ttf
          weight: 900

    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy/Gilroy-Medium.ttf
          weight: 700
        - asset: fonts/Gilroy/Gilroy-Bold.ttf
          weight: 900

    - family: CodePro
      fonts:
        - asset: fonts/CodePro/Code Pro LC.otf
          weight: 400
        - asset: fonts/CodePro/Code Pro Bold LC.otf
          weight: 700

    - family: ReThink-Sans
      fonts:
        - asset: fonts/ReThinkSans/RethinkSans-Regular.otf
          weight: 400
        - asset: fonts/ReThinkSans/RethinkSans-Medium.otf
          weight: 500
        - asset: fonts/ReThinkSans/RethinkSans-SemiBold.otf
          weight: 600
        - asset: fonts/ReThinkSans/RethinkSans-Bold.otf
          weight: 700
        - asset: fonts/ReThinkSans/RethinkSans-ExtraBold.otf
          weight: 800

    - family: NotoSans
      fonts:
        - asset: fonts/Noto/NotoSans.ttf

    - family: Fjalla
      fonts:
        - asset: fonts/Fjalla/FjallaOne-Regular.ttf

    - family: FontAwesome
      fonts:
        - asset: fonts/fontawesome/otfs/FontAwesomeBrandsRegular.otf
          weight: 400
        - asset: fonts/fontawesome/otfs/FontAwesomeFreeRegular.otf
          weight: 400
        - asset: fonts/fontawesome/otfs/FontAwesomeSolid.otf
